"""Markdown formatter for weekly digests (Phase 9)."""

from __future__ import annotations

from datetime import datetime, timezone


def fmt_digest(
    wk: str,
    avg_score: int,
    disk_growth_gb: float,
    top_folder: str,
    critical_events: int,
    new_apps: list[str],
    snapshot_count: int,
) -> str:
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    new_apps_str = (
        "\n".join(f"- {a}" for a in new_apps) if new_apps else "_None detected._"
    )
    disk_sign = "+" if disk_growth_gb >= 0 else ""
    cleanup_note = (
        "Run `machine-state cleanup` to identify reclaimable space."
        if disk_growth_gb > 5
        else "Disk growth is within normal range."
    )

    return f"""# Machine State — {wk}

> Generated {generated} from {snapshot_count} snapshots.

## Health

Average score this week: **{avg_score} / 100**

## Storage

Net disk growth: **{disk_sign}{disk_growth_gb:.2f} GB**
Fastest-growing folder: `{top_folder}`
{cleanup_note}

## Events

Critical events this week: **{critical_events}**

## New applications observed

{new_apps_str}

---
_Generated by machine-state. Run `machine-state digest` to view past reports._
"""
