"""Weekly digest generator — produces a Markdown summary of the past 7 days (Phase 9).

Digests are written to ~/.machine-state/reports/YYYY-WW.md.
They are generated by the scheduler on the first cycle after a week boundary.
"""

from __future__ import annotations

from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

from .. import store
from ..constants import GB, MB

_REPORTS_DIR = Path.home() / ".machine-state" / "reports"


def week_key(dt: datetime | None = None) -> str:
    """Return ISO week string e.g. '2024-W20'."""
    d = dt or datetime.now(timezone.utc)
    return f"{d.isocalendar()[0]}-W{d.isocalendar()[1]:02d}"


def digest_path(wk: str) -> Path:
    return _REPORTS_DIR / f"{wk}.md"


def _week_snapshots(
    all_snapshots: list[dict[str, Any]],
    week_start: datetime,
) -> list[dict[str, Any]]:
    week_end = week_start + timedelta(days=7)
    result = []
    for s in all_snapshots:
        try:
            ts = datetime.fromisoformat(
                str(s.get("timestamp", "")).replace("Z", "+00:00")
            )
        except ValueError:
            continue
        if week_start <= ts < week_end:
            result.append(s)
    return result


def _avg_score(scores: list[dict[str, Any]]) -> int:
    if not scores:
        return 0
    return int(sum(s["score"] for s in scores) / len(scores))


def _disk_growth_gb(snapshots: list[dict[str, Any]]) -> float:
    if len(snapshots) < 2:
        return 0.0
    first = snapshots[0].get("system", {}).get("disk", {})
    last  = snapshots[-1].get("system", {}).get("disk", {})
    delta = int(last.get("usedBytes") or 0) - int(first.get("usedBytes") or 0)
    return round(delta / GB, 2)


def _top_growing_folder(snapshots: list[dict[str, Any]]) -> str:
    sizes: dict[str, int] = {}
    for s in snapshots:
        for proj in s.get("projects", []):
            for item in proj.get("largestItems", []):
                if item.get("type") == "directory":
                    p = item.get("path", "")
                    sizes[p] = max(sizes.get(p, 0), int(item.get("sizeBytes") or 0))
    if not sizes:
        return "—"
    return max(sizes, key=lambda k: sizes[k])


def _critical_event_count(events: list[dict[str, Any]], week_start: datetime) -> int:
    week_end = week_start + timedelta(days=7)
    count = 0
    for e in events:
        try:
            ts = datetime.fromisoformat(e["timestamp"].replace("Z", "+00:00"))
        except (ValueError, KeyError):
            continue
        if week_start <= ts < week_end and e.get("severity") == "critical":
            count += 1
    return count


def _new_apps(snapshots: list[dict[str, Any]]) -> list[str]:
    if len(snapshots) < 2:
        return []
    first_apps = {
        app.get("application")
        for app in snapshots[0].get("derived", {}).get("applications", [])
    }
    last_apps = {
        app.get("application")
        for app in snapshots[-1].get("derived", {}).get("applications", [])
    }
    return sorted(last_apps - first_apps - {None})  # type: ignore[arg-type]


def generate_digest(
    wk: str | None = None,
    db_path: str | Path | None = None,
) -> Path:
    """Generate and write the weekly digest Markdown file.

    Returns the path to the written file.
    """
    target_wk = wk or week_key()
    # Derive week start (Monday 00:00 UTC)
    year, week_num = int(target_wk[:4]), int(target_wk[6:])
    week_start = datetime.fromisocalendar(year, week_num, 1).replace(tzinfo=timezone.utc)

    all_snapshots = store.get_all_snapshots(db_path=db_path, limit=500)
    all_events    = store.get_events(limit=500, db_path=db_path)
    all_scores    = store.get_health_scores(limit=200, db_path=db_path)

    week_snaps  = _week_snapshots(all_snapshots, week_start)
    week_scores = [
        s for s in all_scores
        if week_start.timestamp() <= s["ts"] < (week_start + timedelta(days=7)).timestamp()
    ]

    avg = _avg_score(week_scores)
    disk_growth = _disk_growth_gb(week_snaps)
    top_folder  = _top_growing_folder(week_snaps)
    crit_events = _critical_event_count(all_events, week_start)
    new_apps    = _new_apps(week_snaps)
    from .formatter import fmt_digest
    md = fmt_digest(
        wk=target_wk,
        avg_score=avg,
        disk_growth_gb=disk_growth,
        top_folder=top_folder,
        critical_events=crit_events,
        new_apps=new_apps,
        snapshot_count=len(week_snaps),
    )

    _REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    out = digest_path(target_wk)
    out.write_text(md, encoding="utf-8")
    return out
